<?xml version="1.0" encoding="utf-8"?><Database Name="user" Class="dbUserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\user.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="userConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>